// import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

// const inter = Inter({ subsets: ["latin"] });
const iranYekanRegFont = localFont({
    src: "./../public/Fonts/iranyekanwebregular.woff2",
    // variable: "--IYRFont",
    // style: "swap",
});
const iranYekanFont = localFont({
    src: "./../public/Fonts/iranyekanweblight.woff",
    variable: "--IRFont",
    style: "swap",
});
const strenuousFont = localFont({
    src: "./../public/Fonts/strenuousbl.otf",
    variable: "--STFont",
    style: "swap",
});

export const metadata = {
    title: "فروشگاه دولدور",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${iranYekanRegFont.className} overflow-x-hidden`}>
                <main>
                    {children}
                </main>
            </body>
        </html>
    );
}
