import Providers from "@/Providers/providers";
import MainHeader from "@/components/dashboard/header/main-header";
import NavigationMenu from "@/components/dashboard/navbar/navigation-menu";

export const metadata = {
    title: "فروشگاه دولدور",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <div
            className={`w-screen overflow-x-clip`}>
            <Providers>
                <MainHeader />
                <NavigationMenu />
                {children}
            </Providers>
        </div>
    );
}
